services:
  mongo:
    image: mongo
    container_name: pet-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  server:
    build: ./server
    container_name: pet-server
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/petclinic
      - JWT_SECRET=supersecret

  client:
    build: ./vite-project
    container_name: pet-client
    ports:
      - "5173:5173"
    depends_on:
      - server

volumes:
  mongo_data: